"""
database.py

Módulo responsável pela conexão com o banco de dados do Sistema de
Gestão de Barbearia.

Sem a variável de ambiente DATABASE_URL o banco é um arquivo SQLite
(desenvolvimento local). Com DATABASE_URL (por exemplo
postgresql://usuario:senha@servidor:5432/banco), o banco é o PostgreSQL
(produção). O resto do sistema escreve SQL no formato do SQLite (com ?
nos parâmetros); a conexão com o PostgreSQL traduz o que é diferente.

Uso pela linha de comando:
    python database.py             recria o banco do zero com dados de exemplo
    python database.py --preparar  cria as tabelas se o banco estiver vazio
                                   (sem dados de exemplo) ou atualiza um banco
                                   existente, sem apagar nada; com o banco
                                   sem usuários e DONO_USUARIO/DONO_SENHA
                                   definidas, cria também o primeiro dono
"""

import os
import re
import sqlite3
import sys

import psycopg

DATABASE_PATH = os.path.join(os.path.dirname(__file__), "barbearia.db")

# Erro de restrição (nome de usuário repetido, por exemplo) nos dois bancos.
IntegrityError = (sqlite3.IntegrityError, psycopg.IntegrityError)


def get_database_path():
    """Caminho do banco SQLite: variável de ambiente BARBEARIA_DB ou o padrão."""
    return os.environ.get("BARBEARIA_DB", DATABASE_PATH)


def get_database_url():
    """Endereço do PostgreSQL (variável DATABASE_URL), ou "" para usar o SQLite."""
    return os.environ.get("DATABASE_URL", "").strip()


def usando_postgres():
    return bool(get_database_url())


def get_connection():
    """
    Cria e retorna uma conexão com o banco: PostgreSQL se DATABASE_URL
    estiver definida, senão SQLite. Nos dois casos as colunas podem ser
    lidas pelo nome (linha["nome"]) ou pela posição (linha[0]).
    """
    url = get_database_url()
    if url:
        return _ConexaoPostgres(url)
    conn = sqlite3.connect(get_database_path())
    conn.row_factory = sqlite3.Row  # permite acessar colunas pelo nome
    return conn


# ---------- POSTGRESQL ----------

# Trechos do SQL do SQLite que o PostgreSQL escreve de outro jeito.
_TRADUCOES_POSTGRES = (
    (
        re.compile(r"INTEGER PRIMARY KEY AUTOINCREMENT"),
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    ),
    (re.compile(r"\bREAL\b"), "DOUBLE PRECISION"),
    (
        # Mesmo formato de texto do SQLite: 2024-01-31 18:30:00 (UTC).
        re.compile(r"datetime\('now'\)"),
        "to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')",
    ),
)


def para_postgres(sql, com_parametros=False):
    """
    Traduz um comando escrito para o SQLite. Com parâmetros, troca os ?
    pelos %s do psycopg (e protege os % que já existiam).
    """
    for padrao, troca in _TRADUCOES_POSTGRES:
        sql = padrao.sub(troca, sql)
    if com_parametros:
        sql = sql.replace("%", "%%").replace("?", "%s")
    return sql


class Linha:
    """Linha de resultado do PostgreSQL que funciona como a sqlite3.Row."""

    __slots__ = ("_nomes", "_valores")

    def __init__(self, nomes, valores):
        self._nomes = nomes
        self._valores = tuple(valores)

    def keys(self):
        return list(self._nomes)

    def __getitem__(self, chave):
        if isinstance(chave, (int, slice)):
            return self._valores[chave]
        try:
            return self._valores[self._nomes.index(chave)]
        except ValueError:
            raise IndexError(f"Coluna inexistente: {chave!r}") from None

    def __iter__(self):
        return iter(self._valores)

    def __len__(self):
        return len(self._valores)

    def __repr__(self):
        return f"Linha({dict(zip(self._nomes, self._valores))!r})"


def _fabrica_de_linhas(cursor):
    nomes = tuple(coluna.name for coluna in cursor.description or ())
    return lambda valores: Linha(nomes, valores)


class _ConexaoPostgres:
    """Conexão com o PostgreSQL com a mesma interface usada do sqlite3."""

    def __init__(self, url):
        self._conn = psycopg.connect(url, row_factory=_fabrica_de_linhas)

    def execute(self, sql, parametros=()):
        cursor = self._conn.cursor()
        if parametros:
            cursor.execute(para_postgres(sql, com_parametros=True), parametros)
        else:
            cursor.execute(para_postgres(sql))
        return cursor

    def executescript(self, sql):
        self._conn.execute(para_postgres(sql))

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        self._conn.close()


# ---------- CRIAÇÃO E ATUALIZAÇÃO DAS TABELAS ----------

def _executar_script(nome_arquivo):
    caminho = os.path.join(os.path.dirname(__file__), nome_arquivo)
    conn = get_connection()
    with open(caminho, "r", encoding="utf-8") as f:
        conn.executescript(f.read())
    conn.commit()
    conn.close()


# Tabelas cujos dados pertencem a uma barbearia.
TABELAS_COM_BARBEARIA = ("clientes", "barbeiros", "servicos", "atendimentos", "usuarios")


def _colunas(conn, tabela):
    """Nomes das colunas da tabela (conjunto vazio se ela não existir)."""
    if isinstance(conn, _ConexaoPostgres):
        linhas = conn.execute(
            """
            SELECT column_name AS name FROM information_schema.columns
            WHERE table_schema = current_schema() AND table_name = ?
            """,
            (tabela,),
        )
    else:
        linhas = conn.execute(f"PRAGMA table_info({tabela})")
    return {linha["name"] for linha in linhas}


def _separar_por_barbearia(conn):
    """
    Banco criado antes de existir a tabela barbearias: cria a tabela e
    coloca todos os dados que já existem numa barbearia só.
    """
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS barbearias (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            nome TEXT NOT NULL,
            criado_em TEXT DEFAULT (datetime('now'))
        )
        """
    )
    sem_coluna = [
        tabela for tabela in TABELAS_COM_BARBEARIA
        if _colunas(conn, tabela) and "barbearia_id" not in _colunas(conn, tabela)
    ]
    if not sem_coluna:
        return

    barbearia_id = conn.execute("SELECT MIN(id) FROM barbearias").fetchone()[0]
    if barbearia_id is None:
        barbearia_id = conn.execute(
            "INSERT INTO barbearias (nome) VALUES ('Minha Barbearia') RETURNING id"
        ).fetchone()[0]
    for tabela in sem_coluna:
        # O SQLite só aceita ADD COLUMN NOT NULL com um DEFAULT; ele preenche
        # as linhas antigas. As inserções de models.py sempre informam a
        # barbearia, então o DEFAULT não é usado depois disso.
        conn.execute(
            f"ALTER TABLE {tabela} ADD COLUMN barbearia_id INTEGER NOT NULL "
            f"DEFAULT {int(barbearia_id)} REFERENCES barbearias (id)"
        )


def _gravar_comissao_nos_atendimentos(conn):
    """
    Banco criado antes de o atendimento guardar o percentual de comissão:
    cria a coluna e preenche os atendimentos antigos com o percentual
    atual do barbeiro (o único que se conhece).
    """
    colunas = _colunas(conn, "atendimentos")
    if not colunas or "comissao_percentual" in colunas:
        return
    conn.execute(
        "ALTER TABLE atendimentos ADD COLUMN comissao_percentual REAL NOT NULL DEFAULT 0"
    )
    conn.execute(
        """
        UPDATE atendimentos SET comissao_percentual = COALESCE(
            (SELECT barbeiros.comissao_percentual FROM barbeiros
             WHERE barbeiros.id = atendimentos.barbeiro_id), 0)
        """
    )


# Tabelas cujos registros são desativados em vez de apagados.
TABELAS_COM_ATIVO = ("barbeiros", "servicos", "usuarios")


def _adicionar_coluna_ativo(conn):
    """Banco criado antes das telas de cadastro: todos começam ativos."""
    for tabela in TABELAS_COM_ATIVO:
        if "ativo" not in _colunas(conn, tabela):
            conn.execute(
                f"ALTER TABLE {tabela} ADD COLUMN ativo INTEGER NOT NULL DEFAULT 1"
            )


def atualizar_banco():
    """
    Atualiza um banco antigo sem apagar nada: separa os dados por
    barbearia, grava a comissão em cada atendimento e cria a tabela de
    usuários e a coluna ativo, se ainda não existirem. Pode ser executada
    várias vezes.
    """
    conn = get_connection()
    _separar_por_barbearia(conn)
    _gravar_comissao_nos_atendimentos(conn)
    conn.commit()
    conn.close()
    _executar_script("schema_usuarios.sql")
    conn = get_connection()
    _adicionar_coluna_ativo(conn)
    conn.commit()
    conn.close()


def banco_vazio():
    """True se o banco ainda não tem as tabelas do sistema."""
    conn = get_connection()
    try:
        return not _colunas(conn, "barbearias") and not _colunas(conn, "clientes")
    finally:
        conn.close()


def preparar_banco():
    """
    Deixa o banco pronto sem apagar nada: num banco vazio cria as tabelas
    (sem dados de exemplo); num banco existente, só o atualiza. É o que
    roda antes de iniciar o servidor em produção.
    """
    if banco_vazio():
        _executar_script("schema.sql")
    atualizar_banco()


def criar_primeiro_dono():
    """
    Num banco sem nenhum usuário, cadastra a barbearia e o primeiro dono a
    partir de DONO_USUARIO, DONO_SENHA e BARBEARIA_NOME (opcional). Serve
    para o plano gratuito do Render, que não tem terminal no servidor.
    Depois que existe um usuário, as variáveis são ignoradas. Retorna a
    mensagem para mostrar no log.
    """
    import models  # aqui dentro: models importa este módulo

    conn = get_connection()
    try:
        tem_usuario = conn.execute("SELECT COUNT(*) FROM usuarios").fetchone()[0] > 0
    finally:
        conn.close()
    if tem_usuario:
        return None

    usuario = os.environ.get("DONO_USUARIO", "").strip()
    senha = os.environ.get("DONO_SENHA", "")
    if not (usuario and senha):
        return (
            "Ainda não há nenhum usuário. Defina DONO_USUARIO e DONO_SENHA "
            "e publique de novo para criar o primeiro dono."
        )
    nome = os.environ.get("BARBEARIA_NOME", "").strip() or "Minha Barbearia"
    try:
        models.criar_barbearia_com_dono(nome, usuario, senha)
    except ValueError as erro:
        # Não impede o site de subir; o motivo fica no log do deploy.
        return f"Primeiro dono não criado: {erro}"
    return f"Barbearia {nome!r} criada com o dono {usuario!r}."


def init_db():
    """Recria o banco do zero (apaga tudo) com os dados de exemplo."""
    _executar_script("schema.sql")
    _executar_script("dados_exemplo.sql")
    atualizar_banco()


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    if argv == ["--preparar"]:
        preparar_banco()
        print("Banco de dados pronto.")
        mensagem = criar_primeiro_dono()
        if mensagem:
            print(mensagem)
        return 0
    if argv not in ([], ["--apagar-tudo"]):
        print("Uso: python database.py [--preparar | --apagar-tudo]")
        return 2
    if usando_postgres() and argv != ["--apagar-tudo"]:
        # Proteção para não apagar o banco de produção por engano.
        print(
            "DATABASE_URL está definida: este comando APAGA todos os dados do "
            "PostgreSQL. Para continuar, rode python database.py --apagar-tudo. "
            "Para só criar as tabelas, use python database.py --preparar."
        )
        return 1
    init_db()
    print("Banco de dados inicializado com sucesso.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
