"""
test_producao.py

Preparação para produção: tradução do SQL para o PostgreSQL, linhas do
PostgreSQL que funcionam como as do SQLite, criação das tabelas num banco
vazio sem apagar nada, proteção contra apagar o banco de produção,
cookie seguro e o app rodando de verdade no Gunicorn.

Estes testes rodam no banco escolhido pelo conftest (SQLite, ou o
PostgreSQL de TEST_DATABASE_URL).
"""

import os
import socket
import sqlite3
import subprocess
import sys
import time
import urllib.request

import pytest

import database
import models
from conftest import BARBEARIA

RAIZ = os.path.join(os.path.dirname(__file__), "..")


def _apagar_tabelas():
    conn = database.get_connection()
    for tabela in ("tentativas_login", "usuarios", "atendimentos", "clientes",
                   "servicos", "barbeiros", "barbearias"):
        conn.execute(f"DROP TABLE IF EXISTS {tabela}")
    conn.commit()
    conn.close()


# ---------- TRADUÇÃO PARA O POSTGRESQL ----------

def test_para_postgres_traduz_o_schema():
    sql = database.para_postgres(
        "CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT, preco REAL NOT NULL, "
        "criado_em TEXT DEFAULT (datetime('now')))"
    )
    assert "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in sql
    assert "preco DOUBLE PRECISION NOT NULL" in sql
    assert "now() AT TIME ZONE 'UTC'" in sql
    assert "AUTOINCREMENT" not in sql and "datetime" not in sql


def test_para_postgres_troca_os_parametros():
    sql = database.para_postgres(
        "SELECT * FROM t WHERE nome LIKE '50%' AND id = ? AND x = ?", com_parametros=True
    )
    assert sql == "SELECT * FROM t WHERE nome LIKE '50%%' AND id = %s AND x = %s"


def test_para_postgres_sem_parametros_nao_mexe_no_porcento():
    assert database.para_postgres("SELECT '50%'") == "SELECT '50%'"


def test_linha_funciona_como_a_do_sqlite():
    linha = database.Linha(("id", "nome"), (7, "Carlos"))
    assert linha["nome"] == "Carlos"
    assert linha[0] == 7
    assert linha.keys() == ["id", "nome"]
    assert list(linha) == [7, "Carlos"]
    assert len(linha) == 2
    with pytest.raises(IndexError):
        linha["telefone"]


# ---------- ESCOLHA DO BANCO ----------

def test_sem_database_url_usa_sqlite(monkeypatch, tmp_path):
    monkeypatch.delenv("DATABASE_URL", raising=False)
    monkeypatch.setenv("BARBEARIA_DB", str(tmp_path / "outro.db"))
    conn = database.get_connection()
    assert isinstance(conn, sqlite3.Connection)
    conn.close()
    assert not database.usando_postgres()


def test_testes_nunca_usam_a_database_url_de_producao():
    # No CI, o job do SQLite define TEST_DATABASE_URL como texto vazio.
    assert os.environ.get("DATABASE_URL") == (os.environ.get("TEST_DATABASE_URL") or None)


def test_insert_devolve_o_id_criado():
    primeiro = models.criar_barbeiro(BARBEARIA, "Novo 1", 40)
    segundo = models.criar_barbeiro(BARBEARIA, "Novo 2", 40)
    assert segundo == primeiro + 1
    assert models.buscar_barbeiro(BARBEARIA, segundo)["nome"] == "Novo 2"


# ---------- PREPARAR O BANCO DE PRODUÇÃO ----------

def test_preparar_banco_vazio_cria_as_tabelas_sem_dados_de_exemplo():
    _apagar_tabelas()
    assert database.banco_vazio()

    database.preparar_banco()

    assert not database.banco_vazio()
    assert models.listar_barbearias() == []
    barbearia_id = models.criar_barbearia_com_dono("Barbearia Nova", "novo-dono", "senha-forte")
    assert models.autenticar("novo-dono", "senha-forte")["barbearia_id"] == barbearia_id


def test_preparar_banco_existente_nao_apaga_nada():
    models.criar_cliente(BARBEARIA, "Cliente de Verdade")

    database.preparar_banco()
    database.preparar_banco()  # pode rodar a cada início do servidor

    nomes = [c["nome"] for c in models.listar_clientes(BARBEARIA)]
    assert "Cliente de Verdade" in nomes
    assert models.autenticar("dono", "senha-do-dono") is not None


def test_linha_de_comando_preparar(capsys):
    _apagar_tabelas()
    assert database.main(["--preparar"]) == 0
    assert "pronto" in capsys.readouterr().out
    assert models.listar_barbearias() == []


def test_linha_de_comando_nao_apaga_o_postgres_sem_confirmar(monkeypatch, capsys):
    # Endereço que nem existe: o comando precisa recusar antes de conectar.
    monkeypatch.setenv("DATABASE_URL", "postgresql://ninguem@servidor-inexistente/banco")
    assert database.main([]) == 1
    assert "--apagar-tudo" in capsys.readouterr().out


def test_linha_de_comando_com_opcao_invalida(capsys):
    assert database.main(["--qualquer"]) == 2
    assert "Uso:" in capsys.readouterr().out


# ---------- CONFIGURAÇÃO DE PRODUÇÃO ----------

def _config_do_app(**ambiente):
    resultado = subprocess.run(
        [sys.executable, "-c",
         "import app; print(app.app.config['SESSION_COOKIE_SECURE'])"],
        cwd=RAIZ,
        env={**os.environ, "SECRET_KEY": "x", **ambiente},
        capture_output=True,
        text=True,
        check=True,
    )
    return resultado.stdout.strip()


def test_cookie_seguro_so_com_cookie_seguro_1():
    assert _config_do_app() == "False"
    assert _config_do_app(COOKIE_SEGURO="1") == "True"


def _porta_livre():
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def test_app_roda_no_gunicorn(tmp_path):
    """Sobe o Gunicorn como no Dockerfile e abre a tela de login."""
    porta = _porta_livre()
    ambiente = {**os.environ, "SECRET_KEY": "chave-de-teste",
                "BARBEARIA_DB": str(tmp_path / "gunicorn.db")}
    ambiente.pop("FLASK_DEBUG", None)
    subprocess.run([sys.executable, "database.py", "--preparar"],
                   cwd=RAIZ, env=ambiente, check=True, capture_output=True)
    servidor = subprocess.Popen(
        [sys.executable, "-m", "gunicorn", "app:app", "--bind", f"127.0.0.1:{porta}",
         "--workers", "2"],
        cwd=RAIZ, env=ambiente, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    sem_proxy = urllib.request.build_opener(urllib.request.ProxyHandler({}))
    try:
        limite = time.time() + 30
        while True:
            try:
                with sem_proxy.open(f"http://127.0.0.1:{porta}/login") as resposta:
                    assert resposta.status == 200
                    assert "csrf_token" in resposta.read().decode()
                break
            except OSError:
                if time.time() > limite or servidor.poll() is not None:
                    raise
                time.sleep(0.2)
    finally:
        servidor.terminate()
        servidor.wait(timeout=10)


# ---------- PRIMEIRO DONO PELO DEPLOY ----------

def _sem_variaveis_do_dono(monkeypatch):
    for nome in ("DONO_USUARIO", "DONO_SENHA", "BARBEARIA_NOME"):
        monkeypatch.delenv(nome, raising=False)


def test_preparar_cria_o_primeiro_dono_pelas_variaveis(monkeypatch, capsys):
    _sem_variaveis_do_dono(monkeypatch)
    _apagar_tabelas()
    monkeypatch.setenv("DONO_USUARIO", "primeiro-dono")
    monkeypatch.setenv("DONO_SENHA", "senha-forte")
    monkeypatch.setenv("BARBEARIA_NOME", "Barbearia do Deploy")

    assert database.main(["--preparar"]) == 0

    assert "criada com o dono" in capsys.readouterr().out
    usuario = models.autenticar("primeiro-dono", "senha-forte")
    assert usuario["papel"] == "dono"
    assert [b["nome"] for b in models.listar_barbearias()] == ["Barbearia do Deploy"]


def test_preparar_sem_variaveis_avisa_e_nao_cria_dono(monkeypatch, capsys):
    _sem_variaveis_do_dono(monkeypatch)
    _apagar_tabelas()

    assert database.main(["--preparar"]) == 0

    assert "DONO_USUARIO" in capsys.readouterr().out
    assert models.listar_barbearias() == []


def test_preparar_com_usuario_existente_ignora_as_variaveis(monkeypatch):
    _sem_variaveis_do_dono(monkeypatch)
    monkeypatch.setenv("DONO_USUARIO", "outro-dono")
    monkeypatch.setenv("DONO_SENHA", "senha-forte")
    barbearias_antes = len(models.listar_barbearias())

    assert database.main(["--preparar"]) == 0
    assert database.main(["--preparar"]) == 0

    assert models.autenticar("outro-dono", "senha-forte") is None
    assert len(models.listar_barbearias()) == barbearias_antes


def test_preparar_com_senha_curta_nao_cria_dono_mas_sobe(monkeypatch, capsys):
    _sem_variaveis_do_dono(monkeypatch)
    _apagar_tabelas()
    monkeypatch.setenv("DONO_USUARIO", "primeiro-dono")
    monkeypatch.setenv("DONO_SENHA", "curta")

    assert database.main(["--preparar"]) == 0

    assert "Primeiro dono não criado" in capsys.readouterr().out
    assert models.listar_barbearias() == []
